"""Supabase pgvector Database Schema Definitions

This module defines Pydantic models for pgvector vectors table
as specified in the database schema.
"""

from typing import List, Literal, Optional
from uuid import UUID

from pydantic import BaseModel, Field


VECTOR_TYPES = Literal["chunk", "vlm_region"]


class VectorRecord(BaseModel):
    """Vector embedding record for pgvector storage"""
    vector_id: UUID = Field(..., description="Primary key, matches Neo4j Chunk/VisualFact.vector_id")
    embedding: List[float] = Field(..., description="Vector embedding array")
    document_id: UUID = Field(..., description="Document UUID for cascade deletion")
    chunk_id: Optional[UUID] = Field(None, description="Chunk UUID if type='chunk'")
    fact_id: Optional[UUID] = Field(None, description="VisualFact UUID if type='vlm_region'")
    type: VECTOR_TYPES = Field(..., description="Vector type")
    page: int = Field(..., description="Page number")
    order: int = Field(..., description="Order within document/chunk")

    class Config:
        from_attributes = True  # Enable ORM mode for Supabase/PostgreSQL


class VectorInsert(BaseModel):
    """Model for inserting new vector records (without vector_id, generated by app)"""
    embedding: List[float] = Field(..., description="Vector embedding array")
    document_id: UUID = Field(..., description="Document UUID")
    chunk_id: Optional[UUID] = Field(None, description="Chunk UUID")
    fact_id: Optional[UUID] = Field(None, description="VisualFact UUID")
    type: VECTOR_TYPES = Field(..., description="Vector type")
    page: int = Field(..., description="Page number")
    order: int = Field(..., description="Order within document/chunk")


class VectorQuery(BaseModel):
    """Model for vector similarity search queries"""
    embedding: List[float] = Field(..., description="Query embedding")
    limit: int = Field(10, description="Number of similar vectors to return")
    threshold: Optional[float] = Field(None, description="Similarity threshold")
